stages:
- lint
- test
- build
- deploy

variables:
  GO_VERSION: "1.23.4-alpine"

lint:
  stage: lint
  image: golangci/golangci-lint:v1.55.2-alpine
  script:
    - golangci-lint run --timeout=5m
  allow_failure: true

test:
  stage: test
  image: "golang:$GO_VERSION"
  script:
    - go mod tidy
    - go test ./... -race -covermode=atomic -coverprofile=coverage.out
  artifacts:
    paths: 
      - coverage.out

build:
  stage: build
  image: "golang:$GO_VERSION"
  script:
    - go mod tidy
    - go build -o api
  artifacts:
    paths:
      - api

deploy-on-render:
  stage: deploy
  image: curlimages/curl:latest
  script:
    - echo "Launch Render deployment..."
    - curl https://api.render.com/deploy/$RENDER_SERVICE_NAME?key=$RUNDER_SERVICE_KEY
  when: manual
  only:
    - main