stages:
- deploy

deploy-on-render:
  stage: deploy
  image: curlimages/curl:latest
  script:
    - echo "Launch Render deployment..."
    - curl https://api.render.com/deploy/$RENDER_SERVICE_NAME?key=$RUNDER_SERVICE_KEY
  only:
    - main